modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/Crendgrim/DynamicCrosshair/issues"
license = "LGPL-3.0"

[[mods]]
modId = "dynamiccrosshairapi"
version = "${api_version}"
displayName = "Dynamic Crosshair API"
authors = "Crendgrim"
description = '''
DynamicCrosshair compatibility API
'''
logoFile = "dynamiccrosshair.png"
displayTest = "IGNORE_ALL_VERSION"
