modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Crendgrim/DynamicCrosshair/issues"
license = "LGPL-3.0"

[[mods]]
modId = "dynamiccrosshair"
version = "${version}"
displayName = "Dynamic Crosshair"
authors = "Crendgrim"
description = '''
Dynamic Crosshair that changes shape based on what is targeted
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.dynamiccrosshair]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynamiccrosshair]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynamiccrosshair]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "NONE"
side = "BOTH"
