modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
issueTrackerURL = "https://github.com/Crendgrim/DynamicCrosshair/issues"
license = "LGPL-3.0"

[[mods]]
modId = "dynamiccrosshair"
version = "${version}"
displayName = "Dynamic Crosshair"
authors = "Crendgrim"
description = '''
Dynamic Crosshair that changes shape based on what is targeted
'''
logoFile = "assets/dynamiccrosshair/icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.dynamiccrosshair]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynamiccrosshair]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range_forge}"
ordering = "NONE"
side = "BOTH"
