modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/Crendgrim/DynamicCrosshair/issues"
license = "LGPL-3.0"

[[mods]]
modId = "dynamiccrosshairapi"
version = "${api_version}"
displayName = "Dynamic Crosshair API"
authors = "Crendgrim"
description = '''
DynamicCrosshair compatibility API
'''
logoFile = "dynamiccrosshair.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.dynamiccrosshair]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynamiccrosshair]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range_forge}"
ordering = "NONE"
side = "BOTH"
