modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/Crendgrim/DynamicCrosshair/issues"
license = "LGPL-3.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Crendgrim"
description = '''
Dynamic Crosshair that changes shape based on what is targeted
'''
logoFile = "assets/${id}/icon.png"
logoBlur = false
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "dynamiccrosshair-common.mixins.json"

[[mixins]]
config = "dynamiccrosshair-neoforge.mixins.json"
