modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/Crendgrim/DynamicCrosshair/issues"
license = "LGPL-3.0"

[[mods]]
modId = "dynamiccrosshair"
version = "${version}"
displayName = "Dynamic Crosshair"
authors = "Crendgrim"
description = '''
Dynamic Crosshair that changes shape based on what is targeted
'''
logoFile = "dynamiccrosshair.png"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "dynamiccrosshair-common.mixins.json"

[[dependencies.dynamiccrosshair]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynamiccrosshair]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range_forge}"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynamiccrosshair]]
modId = "yet_another_config_lib"
mandatory = false
versionRange = "${yacl_version_range_neoforge}"
ordering = "NONE"
side = "BOTH"
